export const AWARD_NAMES: string[] = [
  // Valor Awards
  "Medal of Honor",
  "Distinguished Service Cross",
  "Silver Star",
  "Distinguished Flying Cross",
  "Bronze Star with V Device",
  "Soldier's Medal",
  // Meritorious Service
  "Distinguished Service Medal",
  "Defense Distinguished Service Medal",
  "Defense Superior Service Medal",
  "Legion of Merit",
  "Bronze Star Medal",
  "Defense Meritorious Service Medal",
  "Meritorious Service Medal",
  "Joint Service Commendation Medal",
  "Army Commendation Medal",
  "Joint Service Achievement Medal",
  // Service Awards
  "Army Good Conduct Medal",
  "Army Service Ribbon",
  "Army Achievement Medal",
  "Army Overseas Service Ribbon",
  "NCO Professional Development Ribbon",
  "Military Outstanding Volunteer Service Medal",
  "Humanitarian Service Medal",
  "National Defense Service Medal",
  "Armed Forces Service Medal",
  "Global War on Terrorism Service Medal",
  // Campaign & Deployment
  "Purple Heart",
  "Air Medal",
  "Global War on Terrorism Expeditionary Medal",
  "Armed Forces Expeditionary Medal",
  "Korean Defense Service Medal",
  // Unit Awards
  "Presidential Unit Citation",
  "Valorous Unit Award",
  "Meritorious Unit Commendation",
  "Army Superior Unit Award",
  // Combat & Special Skill Badges
  "Combat Infantryman Badge",
  "Combat Infantryman Badge — 2nd Award",
  "Combat Infantryman Badge — 3rd Award",
  "Expert Infantryman Badge",
  "Combat Action Badge",
  "Combat Action Badge — 2nd Award",
  "Combat Action Badge — 3rd Award",
  "Combat Medical Badge",
  "Combat Medical Badge — 2nd Award",
  "Expert Field Medical Badge",
  "Air Assault Badge",
  "Basic Parachutist Badge",
  "Senior Parachutist Badge",
  "Master Parachutist Badge",
  "Parachutist Badge with Combat Jump Star",
  "Army Aviator Badge — Basic",
  "Army Aviator Badge — Senior",
  "Army Aviator Badge — Master",
  "Army Aircrew Badge",
  "French Fourragère",
  // Marksmanship
  "Expert Qualification Badge — Rifle",
  "Sharpshooter Qualification Badge — Rifle",
  "Marksman Qualification Badge — Rifle",
  // Ribbon Devices & Accessories
  "V Device (Valor)",
  "C Device (Combat)",
  "R Device (Remote)",
  "Oak Leaf Clusters",
  "Service Stars",
  "Arrowhead Device",
  "Overseas Service Bars",
];
