/** Maps award names to their insignia image paths */
export const AWARD_IMAGES: Record<string, string> = {
  // Valor
  "Medal of Honor":                           "/insignia/awards/medalofhonor.png",
  "Distinguished Service Cross":              "/insignia/awards/Army-Distinguished-Service-Cross-DSC-69a02199e744d.png",
  "Silver Star":                              "/insignia/awards/Silver-Star-SS-699a020b4c4b4.png",
  "Distinguished Flying Cross":               "/insignia/awards/Distinguished-Flying-Cross-DFC-699a08c29d005.png",
  "Bronze Star with V Device":                "/insignia/awards/Bronze-Star-BSM-699a0ad77858e.png",
  "Soldier's Medal":                          "/insignia/awards/Soldier-s-Medal-SM-699a09c42099c.png",
  // Meritorious
  "Distinguished Service Medal":              "/insignia/awards/Army-Distinguished-Service-DSM-6999fc1392e2a.png",
  "Defense Distinguished Service Medal":      "/insignia/awards/Defense-Distinguished-Service-DDSM-6999f31c67f12.png",
  "Defense Superior Service Medal":           "/insignia/awards/Defense-Superior-Service-DSSM-699a03f7b6167.png",
  "Legion of Merit":                          "/insignia/awards/Legion-of-Merit-LOM-699a053fe0281.png",
  "Bronze Star Medal":                        "/insignia/awards/Bronze-Star-BSM-699a0ad77858e.png",
  "Defense Meritorious Service Medal":        "/insignia/awards/Defense-Meritorious-Service-Medal-DMSM-699a0d1732350.png",
  "Meritorious Service Medal":                "/insignia/awards/Meritorious-Service-Medal-MSM-699a0e0c3d7a6.png",
  "Joint Service Commendation Medal":         "/insignia/awards/Joint-Service-Commendation-JSCOM-699a0fbbb305e.png",
  "Army Commendation Medal":                  "/insignia/awards/Army-Commendation-ARCOM-699a1752d4577.png",
  "Joint Service Achievement Medal":          "/insignia/awards/Joint-Service-Achievement-JSAM-699a184d573d2.png",
  // Service
  "Army Good Conduct Medal":                  "/insignia/awards/Army-Good-Conduct-AGC-69a022009b444.png",
  "Army Service Ribbon":                      "/insignia/awards/Army-Service-Ribbon-ASR-69ce37edc375b.png",
  "Army Achievement Medal":                   "/insignia/awards/Army-Achievement-AAM-69a021c292f66.png",
  "Army Overseas Service Ribbon":             "/insignia/awards/Army-Overseas-Service-Ribbon-OSR-699a1c305f677.png",
  "NCO Professional Development Ribbon":      "/insignia/awards/Army-NCO-Professional-Development-NCOPD-699a1f3c97c16.png",
  "Military Outstanding Volunteer Service Medal": "/insignia/awards/Military-Outstanding-Volunteer-Service-MOV-69ce37fd077b2.png",
  "Humanitarian Service Medal":               "/insignia/awards/Humanitarian-Service-Medal-HSM-699a20f5a9280.png",
  "National Defense Service Medal":           "/insignia/awards/National-Defense-Service-Medal-NDSM-69ce380daeafb.png",
  "Armed Forces Service Medal":               "/insignia/awards/Armed-Forces-Service-Medal-AFSM-699a219573596.png",
  "Global War on Terrorism Service Medal":    "/insignia/awards/Global-War-on-Terrorism-Service-GWOTS-M-699a22561558c.png",
  // Campaign
  "Purple Heart":                             "/insignia/awards/Purple-Heart-PH-699a0bdede6e9.png",
  "Air Medal":                                "/insignia/awards/Air-Medal-AM-699a0f1346d56.png",
  "Global War on Terrorism Expeditionary Medal": "/insignia/awards/Global-War-on-Terrorism-Expeditionary-GWOTE-M-699a236de2648.png",
  "Armed Forces Expeditionary Medal":         "/insignia/awards/uh7JbbW4nw1kh7XAQjUpxug2jo1Rkx91JMswZn5n.png",
  "Korean Defense Service Medal":             "/insignia/awards/Ovby9eQkJB68zvaFM6A8fuZtjJBnmkgbMHJHyRMN.png",
  // Unit
  "Presidential Unit Citation":               "/insignia/awards/tpZE2Z24IDl3rxVXj3Q1FZp59tyowXCpcZ2exRhg.png",
  "Valorous Unit Award":                      "/insignia/awards/TBipLHcSfOXv18Csx3hjavNvjbyJBzxu5YluygEC.png",
  "Meritorious Unit Commendation":            "/insignia/awards/GwGLm6bYDtiJ8hQckoBxvs70w1rgmloxmdMquTPD.png",
  "Army Superior Unit Award":                 "/insignia/awards/KTDCRAeNnspWF3VtZwU47KeNwEj7CSqmiss96D5U.png",
  // Badges
  "Combat Infantryman Badge":                 "/insignia/awards/ngewBvYY762iczHjmcv48W4ukUyxYwJFsKmuDa55.png",
  "Combat Infantryman Badge — 2nd Award":     "/insignia/awards/zbHU1JOteUAPv80gI7zkibnsPtjL75tMO40cLNsn.png",
  "Combat Infantryman Badge — 3rd Award":     "/insignia/awards/3dcolkPhelwZICNJ88YHmRXgXfmHnUAeUlutL4gH.png",
  "Expert Infantryman Badge":                 "/insignia/awards/GDiheaNBTnc9hi5ii8XZi7FjOc6yJ8DV7QlcAx3O.png",
  "Combat Action Badge":                      "/insignia/quals/CAB.png",
  "Combat Action Badge — 2nd Award":          "/insignia/awards/N8ljtw5soK0xdWvfVgSV5L07XWTvhinsyO7VVEav.png",
  "Combat Action Badge — 3rd Award":          "/insignia/awards/BOSehPZHAGlE9AdqbRCFiHC8cX7ooLgxnCRA45aX.png",
  "Combat Medical Badge":                     "/insignia/awards/XOcL7fuH43oEviHaGrIJM1pvioTYw9xPXePtiej8.png",
  "Combat Medical Badge — 2nd Award":         "/insignia/awards/Y0yYUytMNuUXxvmrwiyA7sJMpBbOH590mgqLMLxe.png",
  "Expert Field Medical Badge":               "/insignia/awards/DHzzqF3N0a3z7F9rlrKLo9ttRpWH0npGqQAzFQ5m.png",
  "Air Assault Badge":                        "/insignia/awards/OT67J96ykia5WwuQSt5lqIRd0ZmpYUdfHOq3t7c6.png",
  "Basic Parachutist Badge":                  "/insignia/awards/DZREc7w1vbzlkwdbrYVajyFS4zp2MsUgU8IRiM0j.png",
  "Senior Parachutist Badge":                 "/insignia/awards/Z3wjdgHfHHtIyzmHhJzp5DNidMgQBwPTRa5EiR7D.png",
  "Master Parachutist Badge":                 "/insignia/awards/yge0MNJRT1ZcGDfh1zkDhO10zwAiBql2uEDJBJGu.png",
  "Parachutist Badge with Combat Jump Star":  "/insignia/awards/8N9ocFSxwBtdnLDZPFIqDJDnJyi1lbde906f7K1f.png",
  "Army Aviator Badge — Basic":               "/insignia/awards/661Ew3d1IQs94nWFCsUZv46ZjazGgNqNPOhoPr5s.png",
  "Army Aviator Badge — Senior":              "/insignia/awards/6QeBd0gdPRiwvtFOLpWAbZbAd2NHynh2CWuGCTY3.png",
  "Army Aviator Badge — Master":              "/insignia/awards/HA4KSHyWjzhLITqpZYhBX0xooB0rFLtoS5JlreHz.png",
  "Army Aircrew Badge":                       "/insignia/awards/wEHfpvlozjUZdQ9eDH3GA1oFJyr8bA2v8xsiNLJz.png",
  "French Fourragère":                        "/insignia/awards/BAegToZoacCegjowiUj1hYZDjDGoybHTrJtMFhGu-removebg-preview-693497fd1e113.png",
  // Marksmanship
  "Expert Qualification Badge — Rifle":       "/insignia/awards/OzqUQghMHm2tftxhUcRYNHDkqgTlaTJ9gZK9qciE.png",
  "Sharpshooter Qualification Badge — Rifle": "/insignia/awards/d2j6HF1yZDdIZMAjhYnfXDm4C21kjE8YRO4mHEZ5.png",
  "Marksman Qualification Badge — Rifle":     "/insignia/awards/B8Zuy3fcSqd7F2VdlYKsiDhqLDWNrDZKfod73C6R.png",
  // Devices
  "V Device (Valor)":                         "/insignia/awards/d0YUOgcWa3vDL9k9cqsfMU7e79NrRC1uXBxVRoUY.png",
  "C Device (Combat)":                        "/insignia/awards/RyRuGfjlFNxUXWcj57xBgrRDqJdvDKO4elMgbxLR.png",
  "R Device (Remote)":                        "/insignia/awards/RbXAH9jRnOqq8BfgEqhpE5CwWFkGEumGjdwLggfv.png",
  "Oak Leaf Clusters":                        "/insignia/awards/QXVJojiGGKVBFDl4qovEqesAgmfvlmNYvY5zSUOO.png",
  "Service Stars":                            "/insignia/awards/5RKRBhXNX2D7qM6dCyesjPFUIpyTv1X289Jvl7r2.png",
  "Arrowhead Device":                         "/insignia/awards/Cg7PNXA1njuBZBRaDGDbRDmqEuHfEwg1vH57AFtN.png",
  "Overseas Service Bars":                    "/insignia/awards/JkcBFFyageN1ltFPlwlEgbcVHSPWNyt0n8y9m4DI.png",
};
